
import React, { createContext, useState, useContext, ReactNode } from 'react';
import { Language, UIStrings, AllTranslations } from '../types';

interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  languages: Language[];
  translate: (key: string, fallback?: string, interpolations?: Record<string, string | number>) => string;
}

// Expanded list of languages (around 100 top languages)
// This list can be further expanded. For brevity, I'm adding a significant number.
export const languages: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'zh-CN', name: '中文 (Simplified Chinese)' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'ru', name: 'Русский (Russian)' },
  { code: 'pt-BR', name: 'Português (Brazilian)' },
  { code: 'it', name: 'Italiano (Italian)' },
  { code: 'ko', name: '한국어 (Korean)' },
  { code: 'tr', name: 'Türkçe (Turkish)' },
  { code: 'nl', name: 'Nederlands (Dutch)' },
  { code: 'el', name: 'Ελληνικά (Greek)' },
  { code: 'sv', name: 'Svenska (Swedish)' },
  { code: 'pl', name: 'Polski (Polish)' },
  { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
  { code: 'th', name: 'ไทย (Thai)' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Bahasa Melayu (Malay)' },
  { code: 'he', name: 'עברית (Hebrew)' },
  { code: 'da', name: 'Dansk (Danish)' },
  { code: 'fi', name: 'Suomi (Finnish)' },
  { code: 'no', name: 'Norsk (Norwegian)' },
  { code: 'cs', name: 'Čeština (Czech)' },
  { code: 'hu', name: 'Magyar (Hungarian)' },
  { code: 'ro', name: 'Română (Romanian)' },
  { code: 'sk', name: 'Slovenčina (Slovak)' },
  { code: 'uk', name: 'Українська (Ukrainian)' },
  { code: 'fil', name: 'Filipino (Tagalog)' },
  { code: 'fa', name: 'فارسی (Persian)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'ml', name: 'മലയാളം (Malayalam)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'or', name: 'ଓଡ଼ିଆ (Oriya)' },
  { code: 'as', name: 'অসমীয়া (Assamese)' },
  { code: 'ne', name: 'नेपाली (Nepali)' },
  { code: 'si', name: 'සිංහල (Sinhala)' },
  // ... (add more languages to reach ~100)
  // Europe
  { code: 'bg', name: 'Български (Bulgarian)' },
  { code: 'hr', name: 'Hrvatski (Croatian)' },
  { code: 'sr', name: 'Српски (Serbian)' },
  { code: 'sl', name: 'Slovenščina (Slovenian)' },
  { code: 'et', name: 'Eesti (Estonian)' },
  { code: 'lv', name: 'Latviešu (Latvian)' },
  { code: 'lt', name: 'Lietuvių (Lithuanian)' },
  { code: 'sq', name: 'Shqip (Albanian)' },
  { code: 'mk', name: 'Македонски (Macedonian)' },
  { code: 'mt', name: 'Malti (Maltese)' },
  { code: 'ga', name: 'Gaeilge (Irish)' },
  { code: 'is', name: 'Íslenska (Icelandic)' },
  { code: 'cy', name: 'Cymraeg (Welsh)' },
  { code: 'eu', name: 'Euskara (Basque)' },
  { code: 'ca', name: 'Català (Catalan)' },
  { code: 'gl', name: 'Galego (Galician)' },
  // Asia
  { code: 'my', name: 'မြန်မာ (Burmese)' },
  { code: 'km', name: 'ខ្មែរ (Khmer)' },
  { code: 'lo', name: 'ລາວ (Lao)' },
  { code: 'mn', name: 'Монгол (Mongolian)' },
  { code: 'ka', name: 'ქართული (Georgian)' },
  { code: 'hy', name: 'Հայերեն (Armenian)' },
  { code: 'az', name: 'Azərbaycan (Azerbaijani)' },
  { code: 'kk', name: 'Қазақ (Kazakh)' },
  { code: 'uz', name: 'Oʻzbek (Uzbek)' },
  { code: 'tk', name: 'Türkmen (Turkmen)' },
  { code: 'ky', name: 'Кыргыз (Kyrgyz)' },
  { code: 'tg', name: 'Тоҷикӣ (Tajik)' },
  // Africa
  { code: 'af', name: 'Afrikaans' },
  { code: 'sw', name: 'Kiswahili (Swahili)' },
  { code: 'ha', name: 'Hausa' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'ig', name: 'Igbo' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'st', name: 'Sesotho' },
  { code: 'am', name: 'አማርኛ (Amharic)' },
  { code: 'so', name: 'Soomaali (Somali)' },
  { code: 'mg', name: 'Malagasy' },
  // Add more to complete the list as needed
];

const defaultLanguage: Language = languages.find(lang => lang.code === 'bn') || languages[0]; // Default to Bengali

// Mock translations - in a real app, these would come from JSON files or an i18n library
const translations: AllTranslations = {
  en: {
    appName: 'Vedic Wisdom',
    settingsTitle: 'Settings',
    languageSettingLabel: 'Language',
    themeSettingLabel: 'Theme',
    searchPlaceholder: "Search Vedic wisdom, temples, news...",
    searching: 'Searching...',
    loadingApp: 'Loading...',
    // Auth Page
    authPageWelcome: 'Discover ancient knowledge. Connect with community.',
    continueWithGoogle: 'Continue with Google',
    createAccount: 'Create an Account',
    loginWithEmail: 'Login with Email',
    or: 'OR',
    termsAndPrivacyIntro: 'By continuing, you agree to our ',
    termsOfService: 'Terms of Service',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
    googleSignInFailed: 'Google Sign-In failed. Please try again.',
    // Login Page
    welcomeBack: 'Welcome Back!',
    loginToContinue: 'Login to continue your journey.',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    emailPlaceholder: 'you@example.com',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Login',
    orLoginWith: 'Or login with',
    loginWithGoogleShort: 'Login with Google',
    dontHaveAccount: "Don't have an account?",
    signupNow: 'Sign up now',
    loginFailedInvalid: 'Incorrect email or password.',
    loginFailed: 'Login failed. Please try again.',
    forgotPasswordComingSoon: 'Forgot password feature coming soon!',
    backToOptions: 'Back to options',
    // Signup Page
    createYourAccount: 'Create Your Account',
    joinVedicCommunity: 'Join our community to explore Vedic wisdom.',
    step: 'Step',
    of: 'of',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    countryLabel: 'Country',
    countryPlaceholder: 'e.g., India, Bangladesh',
    stateLabel: 'State/Province',
    statePlaceholder: 'e.g., West Bengal, Dhaka Division',
    cityLabel: 'City/Town',
    cityPlaceholder: 'e.g., Kolkata, Dhaka',
    villageLabel: 'Village/Area (Optional)',
    villagePlaceholder: 'e.g., Shantiniketan, Mirpur',
    phoneLabel: 'Phone Number (with country code)',
    phonePlaceholder: 'e.g., +8801712345678',
    dobLabel: 'Date of Birth',
    languageLabel: 'Preferred Language',
    createPasswordLabel: 'Create Password',
    confirmPasswordLabel: 'Confirm Password',
    nextButton: 'Next',
    createAccountAndVerify: 'Create Account & Verify',
    orSignupWith: 'Or sign up with',
    signupWithGoogleShort: 'Sign up with Google',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Login here',
    nameAndEmailRequired: 'Full Name and Email are required.',
    invalidEmailFormat: 'Please enter a valid email address.',
    passwordMinLength: 'Password must be at least 6 characters.',
    passwordsDoNotMatch: 'Passwords do not match.',
    fillRequiredFields: 'Please fill all required fields.',
    signupFailed: 'Signup failed. Please try again.',
    emailInUse: 'This email is already registered. Try logging in.',
    googleSignUpFailed: 'Google Sign-Up failed. Please try again.',
    previousStep: 'Previous Step',
    // OTP Page
    verifyYourAccount: 'Verify Your Account',
    otpSentTo: 'An OTP has been sent to {recipient}',
    otpIncomplete: 'Please enter the complete OTP.',
    otpInvalid: 'Invalid OTP. Please try again.',
    otpVerificationFailed: 'OTP verification failed.',
    verifyOtpButton: 'Verify OTP',
    didNotReceiveOtp: "Didn't receive the OTP?",
    resendOtp: 'Resend OTP',
    resendingOtp: 'Resending...',
    resendOtpIn: 'Resend OTP in {cooldown}s',
    otpResent: 'A new OTP has been sent to your email.',
    otpResendFailed: 'Failed to resend OTP. Please try again later.',
    backButton: 'Back',
    // Veda Reader Page
    translateTo: 'Translate to',
    reportMantraTitle: 'Report issue with this mantra',
    translationByAI: 'Translation by AI',
    humanVerified: 'Human Verified',
    padaLabel: 'Pada (Key Terms/Word Meanings)',
    padarthaLabel: 'Padartha (Phrase Analysis)',
    bhavarthaLabel: 'Bhavartha (Purport/Essence)',
    translatingTo: 'Translating to {languageName}...',
    previousVerse: 'Previous',
    nextVerse: 'Next',
    selectVersePrompt: 'Select a section, subsection, and verse to display.',
    noVedicTextAvailable: 'No content available for this Vedic text yet.',
    selectTranslationLanguage: 'Select Translation Language',
    searchLanguagesPlaceholder: 'Search languages...',
    noLanguagesFound: 'No languages found matching "{searchTerm}"',
    // Welcome Popup
    welcomePopupTitle: "Welcome to Vedic Wisdom!",
    welcomePopupMessage: "Explore ancient scriptures, connect with our community, and discover spiritual services. Your journey to enlightenment starts here.",
    welcomePopupCta: "Explore Learn Section",
     // AKF Page specific
    akfPageTitle: "AKF Hub & Messages",
    akfSearchPlaceholder: "Search persons, orgs, temples...",
    messageRequestSent: "Message request sent to {name}.",
    requestSentButton: "Request Sent",
    sendMessageRequestButton: "Message Request",
    incomingRequestsTitle: "Incoming Message Requests",
    noIncomingRequests: "No new message requests.",
    recentChatsTitle: "Recent Chats",
    noRecentChats: "No recent chats. Accept requests or search to connect.",
    noEntitiesMatchSearch: "No entities match your search.",
    confirmProfileDelete: "Are you sure you want to delete the chat with {name}? This action cannot be undone.",
    messageAutoCleared: "Message has been automatically cleared.",
    noMessagesInChat: "No messages in this chat or they have been cleared.",
    messagesAutoDeleteNote: "Messages are for temporary viewing and will be cleared automatically.",
    requestAcceptedStartChat: "You accepted the message request from {name}. You can now chat.",
    visitWebsiteButton: "Visit Our Website",
    websiteConfirmTitle: "Confirm Navigation",
    websiteConfirmMessage: "Do you want to visit our website? AKFBD.ORG",
    visitButton: "Visit",
    cancelButton: "Cancel",
    viewingWebsiteTitle: "Viewing AKFBD.ORG",
    closeInAppBrowserAria: "Close website view",
    typeMessagePlaceholder: "Type a message...",
    sendMessageButtonAria: "Send message",
    akfChatMockReply: "I received your message: \"{message}\". This is an automated AKF Hub reply.",
    startTypingToChat: "You can start typing to chat with {name}.",
    akfSearchPlaceholderAria: "Search for people, organizations, or temples in the AKF Hub",
    deleteProfileAria: "Delete chat with {name}",

    // Help & Support Page
    helpSupportTitle: "Help & Support",
    faqTitle: "Frequently Asked Questions",
    contactUsTitle: "Contact Us",
    liveChatTitle: "Live Chat",
    faq_q1_change_language: "How do I change the app language?",
    faq_a1_change_language_ans: "You can change the app language from the Settings page. Tap on your profile icon, then go to Settings and select 'Language'.",
    faq_q2_search_content: "How can I search for specific content?",
    faq_a2_search_content_ans: "Use the search bar located on the Home page. You can type keywords related to Vedic texts, news, yoga, or other services.",
    faq_q3_report_issue: "How do I report an issue or provide feedback?",
    faq_a3_report_issue_ans: "For issues with Vedic text translations, use the 'Report' button on the Veda Reader page. For general app feedback or other issues, please use the Contact Us section or Live Chat on this page.",
    contactSupportText: "For further assistance, you can reach us at:",
    supportEmail: "support@vedicwisdomapp.com",
    supportPhone: "+1-800-VEDIC-HLP",
    startLiveChatButton: "Start Live Chat",
    liveSupportChatHeader: "Live Support Chat",
    typeYourMessagePlaceholder: "Type your message...",
    sendChatMessageAria: "Send chat message",
    closeChatAria: "Close chat",
    supportChatWelcome: "Hello! How can we assist you today?",
    supportChatGenericReply: "Thank you for your message. An agent will be with you shortly.",
    supportChatPasswordHelp: "For password issues, please try the \"Forgot Password\" link on the login page or contact support@vedicwisdomapp.com.",
    supportChatPaymentHelp: "For payment queries, please ensure your payment method is valid or contact us with transaction details."
  },
  bn: {
    appName: 'বৈদিক জ্ঞান',
    settingsTitle: 'সেটিংস',
    languageSettingLabel: 'ভাষা',
    themeSettingLabel: 'থিম',
    searchPlaceholder: "বৈদিক জ্ঞান, মন্দির, সংবাদ অনুসন্ধান করুন...",
    searching: 'অনুসন্ধান করা হচ্ছে...',
    loadingApp: 'লোড হচ্ছে...',
    // Auth Page
    authPageWelcome: 'প্রাচীন জ্ঞান অন্বেষণ করুন। সম্প্রদায়ের সাথে সংযোগ স্থাপন করুন।',
    continueWithGoogle: 'Google দিয়ে চালিয়ে যান',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    loginWithEmail: 'ইমেইল দিয়ে লগইন করুন',
    or: 'অথবা',
    termsAndPrivacyIntro: 'চালিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের ',
    termsOfService: 'পরিষেবার শর্তাবলী',
    and: ' এবং ',
    privacyPolicy: 'গোপনীয়তা নীতিতে',
    googleSignInFailed: 'Google সাইন-ইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    // Login Page
    welcomeBack: 'পুনরায় স্বাগতম!',
    loginToContinue: 'আপনার যাত্রা চালিয়ে যেতে লগইন করুন।',
    emailLabel: 'ইমেইল ঠিকানা',
    passwordLabel: 'পাসওয়ার্ড',
    emailPlaceholder: 'your@example.com',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    loginButton: 'লগইন',
    orLoginWith: 'অথবা লগইন করুন',
    loginWithGoogleShort: 'Google দিয়ে লগইন',
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    signupNow: 'এখন সাইন আপ করুন',
    loginFailedInvalid: 'ভুল ইমেইল বা পাসওয়ার্ড।',
    loginFailed: 'লগইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    forgotPasswordComingSoon: 'পাসওয়ার্ড ভুলে গেছেন বৈশিষ্ট্য শীঘ্রই আসছে!',
    backToOptions: 'বিকল্পগুলিতে ফিরে যান',
    // Signup Page
    createYourAccount: 'আপনার অ্যাকাউন্ট তৈরি করুন',
    joinVedicCommunity: 'বৈদিক জ্ঞান অন্বেষণ করতে আমাদের সম্প্রদায়ে যোগ দিন।',
    step: 'ধাপ',
    of: '/',
    fullNameLabel: 'পুরো নাম',
    fullNamePlaceholder: 'আপনার পুরো নাম লিখুন',
    countryLabel: 'দেশ',
    countryPlaceholder: 'যেমন: ভারত, বাংলাদেশ',
    stateLabel: 'রাজ্য/বিভাগ',
    statePlaceholder: 'যেমন: পশ্চিমবঙ্গ, ঢাকা বিভাগ',
    cityLabel: 'শহর/নগর',
    cityPlaceholder: 'যেমন: কলকাতা, ঢাকা',
    villageLabel: 'গ্রাম/এলাকা (ঐচ্ছিক)',
    villagePlaceholder: 'যেমন: শান্তিনিকেতন, মিরপুর',
    phoneLabel: 'ফোন নম্বর (দেশের কোড সহ)',
    phonePlaceholder: 'যেমন: +৮৮০১৭২৩৪৫৬৭৮',
    dobLabel: 'জন্ম তারিখ',
    languageLabel: 'পছন্দের ভাষা',
    createPasswordLabel: 'পাসওয়ার্ড তৈরি করুন',
    confirmPasswordLabel: 'পাসওয়ার্ড নিশ্চিত করুন',
    nextButton: 'পরবর্তী',
    createAccountAndVerify: 'অ্যাকাউন্ট তৈরি ও যাচাই করুন',
    orSignupWith: 'অথবা সাইন আপ করুন',
    signupWithGoogleShort: 'Google দিয়ে সাইন আপ',
    alreadyHaveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    loginLink: 'এখানে লগইন করুন',
    nameAndEmailRequired: 'পুরো নাম এবং ইমেইল আবশ্যক।',
    invalidEmailFormat: 'অনুগ্রহ করে একটি বৈধ ইমেইল ঠিকানা লিখুন।',
    passwordMinLength: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    passwordsDoNotMatch: 'পাসওয়ার্ড মেলেনি।',
    fillRequiredFields: 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
    signupFailed: 'সাইন আপ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    emailInUse: 'এই ইমেইল ইতিমধ্যে নিবন্ধিত। লগইন করার চেষ্টা করুন।',
    googleSignUpFailed: 'Google সাইন-আপ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    previousStep: 'পূর্ববর্তী ধাপ',
    // OTP Page
    verifyYourAccount: 'আপনার অ্যাকাউন্ট যাচাই করুন',
    otpSentTo: 'একটি OTP পাঠানো হয়েছে {recipient} এই ঠিকানায়',
    otpIncomplete: 'অনুগ্রহ করে সম্পূর্ণ OTP লিখুন।',
    otpInvalid: 'অবৈধ OTP। অনুগ্রহ করে আবার চেষ্টা করুন।',
    otpVerificationFailed: 'OTP যাচাইকরণ ব্যর্থ হয়েছে।',
    verifyOtpButton: 'OTP যাচাই করুন',
    didNotReceiveOtp: "OTP পাননি?",
    resendOtp: 'OTP পুনরায় পাঠান',
    resendingOtp: 'পুনরায় পাঠানো হচ্ছে...',
    resendOtpIn: '{cooldown} সেকেন্ডে OTP পুনরায় পাঠান',
    otpResent: 'আপনার ইমেইলে একটি নতুন OTP পাঠানো হয়েছে।',
    otpResendFailed: 'OTP পুনরায় পাঠাতে ব্যর্থ হয়েছে। অনুগ্রহ করে পরে আবার চেষ্টা করুন।',
    backButton: 'ফিরে যান',
    // Veda Reader Page
    translateTo: 'অনুবাদ করুন',
    reportMantraTitle: 'এই মন্ত্রে সমস্যা রিপোর্ট করুন',
    translationByAI: 'AI দ্বারা অনুবাদিত',
    humanVerified: 'মানুষ দ্বারা যাচাইকৃত',
    padaLabel: 'পদ (মূল শব্দ/শব্দার্থ)',
    padarthaLabel: 'পদার্থ (বাক্যাংশ বিশ্লেষণ)',
    bhavarthaLabel: 'ভাবার্থ (তাৎপর্য/মূলভাব)',
    translatingTo: '{languageName} ভাষায় অনুবাদ করা হচ্ছে...',
    previousVerse: 'পূর্ববর্তী',
    nextVerse: 'পরবর্তী',
    selectVersePrompt: 'দেখার জন্য একটি বিভাগ, উপবিভাগ এবং শ্লোক নির্বাচন করুন।',
    noVedicTextAvailable: 'এই বৈদিক পাঠ্যের জন্য এখনও কোনও সামগ্রী উপলব্ধ নেই।',
    selectTranslationLanguage: 'অনুবাদ ভাষা নির্বাচন করুন',
    searchLanguagesPlaceholder: 'ভাষা অনুসন্ধান করুন...',
    noLanguagesFound: '"{searchTerm}" এর সাথে মেলে এমন কোনও ভাষা খুঁজে পাওয়া যায়নি',
    // Welcome Popup
    welcomePopupTitle: "বৈদিক জ্ঞানে স্বাগতম!",
    welcomePopupMessage: "প্রাচীন শাস্ত্র অন্বেষণ করুন, আমাদের সম্প্রদায়ের সাথে যুক্ত হন এবং আধ্যাত্মিক পরিষেবাগুলি আবিষ্কার করুন। আপনার জ্ঞানার্জনের যাত্রা এখান থেকেই শুরু।",
    welcomePopupCta: "শিক্ষা বিভাগ দেখুন",
     // AKF Page specific
    akfPageTitle: "AKF হাব ও বার্তা",
    akfSearchPlaceholder: "ব্যক্তি, সংস্থা, মন্দির অনুসন্ধান করুন...",
    messageRequestSent: "{name} কে বার্তা অনুরোধ পাঠানো হয়েছে।",
    requestSentButton: "অনুরোধ পাঠানো হয়েছে",
    sendMessageRequestButton: "বার্তা অনুরোধ",
    incomingRequestsTitle: "আগত বার্তা অনুরোধ",
    noIncomingRequests: "কোনো নতুন বার্তা অনুরোধ নেই।",
    recentChatsTitle: "সাম্প্রতিক চ্যাট",
    noRecentChats: "কোনো সাম্প্রতিক চ্যাট নেই। অনুরোধ গ্রহণ করুন অথবা সংযোগ করতে অনুসন্ধান করুন।",
    noEntitiesMatchSearch: "আপনার অনুসন্ধানের সাথে মেলে এমন কোনো সত্তা পাওয়া যায়নি।",
    confirmProfileDelete: "আপনি কি {name} এর সাথে চ্যাট মুছে ফেলতে চান? এই কাজটি আর ফেরানো যাবে না।",
    messageAutoCleared: "বার্তা স্বয়ংক্রিয়ভাবে পরিষ্কার করা হয়েছে।",
    noMessagesInChat: "এই চ্যাটে কোনো বার্তা নেই অথবা সেগুলি পরিষ্কার করা হয়েছে।",
    messagesAutoDeleteNote: "বার্তাগুলি অস্থায়ীভাবে দেখার জন্য এবং স্বয়ংক্রিয়ভাবে পরিষ্কার হয়ে যাবে।",
    requestAcceptedStartChat: "{name} এর বার্তা অনুরোধ আপনি গ্রহণ করেছেন। এখন চ্যাট করতে পারেন।",
    visitWebsiteButton: "আমাদের ওয়েবসাইট দেখুন",
    websiteConfirmTitle: "স্থানান্তর নিশ্চিত করুন",
    websiteConfirmMessage: "আপনি কি আমাদের ওয়েবসাইট AKFBD.ORG দেখতে চান?",
    visitButton: "দেখুন",
    cancelButton: "বাতিল",
    viewingWebsiteTitle: "AKFBD.ORG দেখা হচ্ছে",
    closeInAppBrowserAria: "ওয়েবসাইট ভিউ বন্ধ করুন",
    typeMessagePlaceholder: "বার্তা টাইপ করুন...",
    sendMessageButtonAria: "বার্তা পাঠান",
    akfChatMockReply: "আপনার বার্তা \"{message}\" পেয়েছি। এটি একটি স্বয়ংক্রিয় AKF হাব উত্তর।",
    startTypingToChat: "{name} এর সাথে চ্যাট করতে টাইপ করা শুরু করতে পারেন।",
    akfSearchPlaceholderAria: "AKF হাবে ব্যক্তি, সংস্থা বা মন্দির অনুসন্ধান করুন",
    deleteProfileAria: "{name} এর সাথে চ্যাট মুছুন",

    // Help & Support Page
    helpSupportTitle: "সাহায্য ও সহায়তা",
    faqTitle: "সাধারণ জিজ্ঞাস্য প্রশ্নাবলী (FAQ)",
    contactUsTitle: "যোগাযোগ করুন",
    liveChatTitle: "লাইভ চ্যাট",
    faq_q1_change_language: "আমি কীভাবে অ্যাপের ভাষা পরিবর্তন করব?",
    faq_a1_change_language_ans: "আপনি সেটিংস পৃষ্ঠা থেকে অ্যাপের ভাষা পরিবর্তন করতে পারেন। আপনার প্রোফাইল আইকনে ট্যাপ করুন, তারপর সেটিংসে যান এবং 'ভাষা' নির্বাচন করুন।",
    faq_q2_search_content: "আমি কীভাবে নির্দিষ্ট বিষয়বস্তু অনুসন্ধান করতে পারি?",
    faq_a2_search_content_ans: "মূল পৃষ্ঠায় অবস্থিত অনুসন্ধান বারটি ব্যবহার করুন। আপনি বৈদিক গ্রন্থ, সংবাদ, যোগ বা অন্যান্য পরিষেবা সম্পর্কিত ключові слова টাইপ করতে পারেন।",
    faq_q3_report_issue: "আমি কীভাবে কোনও সমস্যা রিপোর্ট করব বা প্রতিক্রিয়া জানাব?",
    faq_a3_report_issue_ans: "বৈদিক পাঠ্য অনুবাদে সমস্যার জন্য, বেদ পাঠক পৃষ্ঠায় 'রিপোর্ট' বোতামটি ব্যবহার করুন। সাধারণ অ্যাপ প্রতিক্রিয়া বা অন্যান্য সমস্যার জন্য, দয়া করে এই পৃষ্ঠায় আমাদের সাথে যোগাযোগ করুন বিভাগ বা লাইভ চ্যাট ব্যবহার করুন।",
    contactSupportText: "আরও সহায়তার জন্য, আপনি আমাদের সাথে এখানে যোগাযোগ করতে পারেন:",
    supportEmail: "support@vedicwisdomapp.com",
    supportPhone: "+৮৮০-XXX-XXXXXX",
    startLiveChatButton: "লাইভ চ্যাট শুরু করুন",
    liveSupportChatHeader: "লাইভ সাপোর্ট চ্যাট",
    typeYourMessagePlaceholder: "আপনার বার্তা টাইপ করুন...",
    sendChatMessageAria: "চ্যাট বার্তা পাঠান",
    closeChatAria: "চ্যাট বন্ধ করুন",
    supportChatWelcome: "নমস্কার! আমরা আপনাকে কীভাবে সহায়তা করতে পারি?",
    supportChatGenericReply: "আপনার বার্তার জন্য ধন্যবাদ। একজন প্রতিনিধি শীঘ্রই আপনার সাথে যোগাযোগ করবেন।",
    supportChatPasswordHelp: "পাসওয়ার্ড সংক্রান্ত সমস্যার জন্য, অনুগ্রহ করে লগইন পৃষ্ঠায় \"পাসওয়ার্ড ভুলে গেছেন\" লিঙ্কটি চেষ্টা করুন অথবা support@vedicwisdomapp.com এ যোগাযোগ করুন।",
    supportChatPaymentHelp: "অর্থপ্রদান সংক্রান্ত প্রশ্নের জন্য, অনুগ্রহ করে নিশ্চিত করুন আপনার অর্থপ্রদানের পদ্ধতিটি বৈধ অথবা লেনদেনের বিবরণ সহ আমাদের সাথে যোগাযোগ করুন।"
  },
  hi: {
    appName: 'वैदिक ज्ञान',
    settingsTitle: 'समायोजन',
    languageSettingLabel: 'भाषा',
    themeSettingLabel: 'थीम',
    searchPlaceholder: "वैदिक ज्ञान, मंदिर, समाचार खोजें...",
    searching: 'खोज रहा है...',
    loadingApp: 'लोड हो रहा है...',
     // Auth Page
    authPageWelcome: 'प्राचीन ज्ञान की खोज करें। समुदाय से जुड़ें।',
    continueWithGoogle: 'Google के साथ जारी रखें',
    createAccount: 'खाता बनाएं',
    loginWithEmail: 'ईमेल से लॉगिन करें',
    or: 'अथवा',
    termsAndPrivacyIntro: 'जारी रखकर, आप हमारी ',
    termsOfService: 'सेवा की शर्तों',
    and: ' और ',
    privacyPolicy: 'गोपनीयता नीति',
    googleSignInFailed: 'Google साइन-इन विफल रहा। कृपया पुनः प्रयास करें।',
    // Login Page
    welcomeBack: 'पुनः स्वागत है!',
    loginToContinue: 'अपनी यात्रा जारी रखने के लिए लॉगिन करें।',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    emailPlaceholder: 'आपका@example.com',
    forgotPassword: 'पासवर्ड भूल गए?',
    loginButton: 'लॉगिन',
    orLoginWith: 'या इसके साथ लॉगिन करें',
    loginWithGoogleShort: 'Google से लॉगिन',
    dontHaveAccount: "खाता नहीं है?",
    signupNow: 'अभी साइन अप करें',
    loginFailedInvalid: 'गलत ईमेल या पासवर्ड।',
    loginFailed: 'लॉगिन विफल। कृपया पुनः प्रयास करें।',
    forgotPasswordComingSoon: 'पासवर्ड भूल गए सुविधा जल्द ही आ रही है!',
    backToOptions: 'विकल्पों पर वापस जाएं',
    // Signup Page
    createYourAccount: 'अपना खाता बनाएं',
    joinVedicCommunity: 'वैदिक ज्ञान का अन्वेषण करने के लिए हमारे समुदाय में शामिल हों।',
    step: 'चरण',
    of: '/',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
    countryLabel: 'देश',
    countryPlaceholder: 'जैसे, भारत, बांग्लादेश',
    stateLabel: 'राज्य/प्रांत',
    statePlaceholder: 'जैसे, पश्चिम बंगाल, ढाका डिवीजन',
    cityLabel: 'शहर/नगर',
    cityPlaceholder: 'जैसे, कोलकाता, ढाका',
    villageLabel: 'गाँव/क्षेत्र (वैकल्पिक)',
    villagePlaceholder: 'जैसे, शांतिनिकेतन, मीरपुर',
    phoneLabel: 'फ़ोन नंबर (देश कोड के साथ)',
    phonePlaceholder: 'जैसे, +919876543210',
    dobLabel: 'जन्म तिथि',
    languageLabel: ' पसंदीदा भाषा',
    createPasswordLabel: 'पासवर्ड बनाएं',
    confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
    nextButton: 'अगला',
    createAccountAndVerify: 'खाता बनाएं और सत्यापित करें',
    orSignupWith: 'या इसके साथ साइन अप करें',
    signupWithGoogleShort: 'Google से साइन अप',
    alreadyHaveAccount: 'पहले से ही एक खाता है?',
    loginLink: 'यहां लॉगिन करें',
    nameAndEmailRequired: 'पूरा नाम और ईमेल आवश्यक हैं।',
    invalidEmailFormat: 'कृपया एक वैध ईमेल पता दर्ज करें।',
    passwordMinLength: 'पासवर्ड कम से कम 6 वर्णों का होना चाहिए।',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते।',
    fillRequiredFields: 'कृपया सभी आवश्यक फ़ील्ड भरें।',
    signupFailed: 'साइन अप विफल। कृपया पुनः प्रयास करें।',
    emailInUse: 'यह ईमेल पहले से पंजीकृत है। लॉगिन करने का प्रयास करें।',
    googleSignUpFailed: 'Google साइन-अप विफल रहा। कृपया पुनः प्रयास करें।',
    previousStep: 'पिछला चरण',
    // OTP Page
    verifyYourAccount: 'अपना खाता सत्यापित करें',
    otpSentTo: 'एक OTP {recipient} पर भेजा गया है',
    otpIncomplete: 'कृपया पूरा OTP दर्ज करें।',
    otpInvalid: 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    otpVerificationFailed: 'OTP सत्यापन विफल।',
    verifyOtpButton: 'OTP सत्यापित करें',
    didNotReceiveOtp: "OTP प्राप्त नहीं हुआ?",
    resendOtp: 'OTP पुनः भेजें',
    resendingOtp: 'पुनः भेजा जा रहा है...',
    resendOtpIn: '{cooldown} सेकंड में OTP पुनः भेजें',
    otpResent: 'आपके ईमेल पर एक नया OTP भेजा गया है।',
    otpResendFailed: 'OTP पुनः भेजने में विफल। कृपया बाद में पुनः प्रयास करें।',
    backButton: 'वापस',
    // Veda Reader Page
    translateTo: 'में अनुवाद करें',
    reportMantraTitle: 'इस मंत्र के साथ समस्या की रिपोर्ट करें',
    translationByAI: 'AI द्वारा अनुवादित',
    humanVerified: 'मानव द्वारा सत्यापित',
    padaLabel: 'पद (मुख्य शब्द/शब्दार्थ)',
    padarthaLabel: 'पदार्थ (वाक्यांश विश्लेषण)',
    bhavarthaLabel: 'भावार्थ (तात्पर्य/मूलभाव)',
    translatingTo: '{languageName} में अनुवाद किया जा रहा है...',
    previousVerse: 'पिछला',
    nextVerse: 'अगला',
    selectVersePrompt: 'प्रदर्शित करने के लिए एक खंड, उपखंड और श्लोक चुनें।',
    noVedicTextAvailable: 'इस वैदिक पाठ के लिए अभी कोई सामग्री उपलब्ध नहीं है।',
    selectTranslationLanguage: 'अनुवाद भाषा चुनें',
    searchLanguagesPlaceholder: 'भाषा खोजें...',
    noLanguagesFound: '"{searchTerm}" से मेल खाने वाली कोई भाषा नहीं मिली',
    // Welcome Popup
    welcomePopupTitle: "वैदिक ज्ञान में आपका स्वागत है!",
    welcomePopupMessage: "प्राचीन ग्रंथों का अन्वेषण करें, हमारे समुदाय से जुड़ें, और आध्यात्मिक सेवाओं की खोज करें। आपके ज्ञानोदय की यात्रा यहीं से शुरू होती है।",
    welcomePopupCta: "शिक्षा अनुभाग देखें",
     // AKF Page specific
    akfPageTitle: "AKF हब और संदेश",
    akfSearchPlaceholder: "व्यक्तियों, संगठनों, मंदिरों की खोज करें...",
    messageRequestSent: "{name} को संदेश अनुरोध भेजा गया।",
    requestSentButton: "अनुरोध भेजा गया",
    sendMessageRequestButton: "संदेश अनुरोध",
    incomingRequestsTitle: "आने वाले संदेश अनुरोध",
    noIncomingRequests: "कोई नया संदेश अनुरोध नहीं।",
    recentChatsTitle: "हाल के चैट",
    noRecentChats: "कोई हालिया चैट नहीं। अनुरोध स्वीकार करें या जुड़ने के लिए खोजें।",
    noEntitiesMatchSearch: "आपकी खोज से कोई निकाय मेल नहीं खाता।",
    confirmProfileDelete: "क्या आप वाकई {name} के साथ चैट हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।",
    messageAutoCleared: "संदेश स्वचालित रूप से साफ़ कर दिया गया है।",
    noMessagesInChat: "इस चैट में कोई संदेश नहीं है या वे साफ़ कर दिए गए हैं।",
    messagesAutoDeleteNote: "संदेश अस्थायी देखने के लिए हैं और स्वचालित रूप से साफ़ हो जाएंगे।",
    requestAcceptedStartChat: "आपने {name} का संदेश अनुरोध स्वीकार कर लिया है। अब आप चैट कर सकते हैं।",
    visitWebsiteButton: "हमारी वेबसाइट पर जाएँ",
    websiteConfirmTitle: "नेविगेशन की पुष्टि करें",
    websiteConfirmMessage: "क्या आप हमारी वेबसाइट AKFBD.ORG पर जाना चाहते हैं?",
    visitButton: "जाएँ",
    cancelButton: "रद्द करें",
    viewingWebsiteTitle: "AKFBD.ORG देखा जा रहा है",
    closeInAppBrowserAria: "वेबसाइट दृश्य बंद करें",
    typeMessagePlaceholder: "संदेश टाइप करें...",
    sendMessageButtonAria: "संदेश भेजें",
    akfChatMockReply: "आपका संदेश \"{message}\" प्राप्त हुआ। यह एक स्वचालित AKF हब उत्तर है।",
    startTypingToChat: "{name} के साथ चैट करने के लिए टाइप करना शुरू कर सकते हैं।",
    akfSearchPlaceholderAria: "AKF हब में लोगों, संगठनों या मंदिरों को खोजें",
    deleteProfileAria: "{name} के साथ चैट हटाएं",
    
    // Help & Support Page
    helpSupportTitle: "सहायता और समर्थन",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
    contactUsTitle: "हमसे संपर्क करें",
    liveChatTitle: "लाइव चैट",
    faq_q1_change_language: "मैं ऐप की भाषा कैसे बदलूं?",
    faq_a1_change_language_ans: "आप सेटिंग्स पृष्ठ से ऐप की भाषा बदल सकते हैं। अपने प्रोफ़ाइल आइकन पर टैप करें, फिर सेटिंग्स पर जाएं और 'भाषा' चुनें।",
    faq_q2_search_content: "मैं विशिष्ट सामग्री कैसे खोज सकता हूं?",
    faq_a2_search_content_ans: "होम पेज पर स्थित सर्च बार का उपयोग करें। आप वैदिक ग्रंथों, समाचारों, योग या अन्य सेवाओं से संबंधित कीवर्ड टाइप कर सकते हैं।",
    faq_q3_report_issue: "मैं किसी समस्या की रिपोर्ट कैसे करूं या प्रतिक्रिया कैसे दूं?",
    faq_a3_report_issue_ans: "वैदिक पाठ अनुवाद में समस्याओं के लिए, वेद रीडर पृष्ठ पर 'रिपोर्ट' बटन का उपयोग करें। सामान्य ऐप प्रतिक्रिया या अन्य समस्याओं के लिए, कृपया इस पृष्ठ पर हमसे संपर्क करें अनुभाग या लाइव चैट का उपयोग करें।",
    contactSupportText: "अधिक सहायता के लिए, आप हमसे यहां संपर्क कर सकते हैं:",
    supportEmail: "support@vedicwisdomapp.com",
    supportPhone: "+91-XXX-XXXXXXX",
    startLiveChatButton: "लाइव चैट शुरू करें",
    liveSupportChatHeader: "लाइव सहायता चैट",
    typeYourMessagePlaceholder: "अपना संदेश टाइप करें...",
    sendChatMessageAria: "चैट संदेश भेजें",
    closeChatAria: "चैट बंद करें",
    supportChatWelcome: "नमस्ते! हम आज आपकी कैसे सहायता कर सकते हैं?",
    supportChatGenericReply: "आपके संदेश के लिए धन्यवाद। एक एजेंट शीघ्र ही आपके साथ होगा।",
    supportChatPasswordHelp: "पासवर्ड समस्याओं के लिए, कृपया लॉगिन पृष्ठ पर \"पासवर्ड भूल गए\" लिंक का प्रयास करें या support@vedicwisdomapp.com पर संपर्क करें।",
    supportChatPaymentHelp: "भुगतान प्रश्नों के लिए, कृपया सुनिश्चित करें कि आपकी भुगतान विधि मान्य है या लेनदेन विवरण के साथ हमसे संपर्क करें।"
  },
  // Add more translations as needed
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<Language>(() => {
    const storedLangCode = localStorage.getItem('vedicAppLanguage');
    if (storedLangCode) {
      const storedLang = languages.find(l => l.code === storedLangCode);
      if (storedLang) return storedLang;
    }
    // Default to Bengali or English if Bengali is not found (should not happen with current languages list)
    return languages.find(l => l.code === 'bn') || defaultLanguage;
  });

  const setCurrentLanguage = (language: Language) => {
    const foundLanguage = languages.find(l => l.code === language.code);
    const langToSet = foundLanguage || defaultLanguage;
    setCurrentLanguageState(langToSet);
    localStorage.setItem('vedicAppLanguage', langToSet.code);
  };
  
  const translate = (key: string, fallback?: string, interpolations?: Record<string, string | number>): string => {
    const langCode = currentLanguage.code;
    let translation = translations[langCode]?.[key] || translations.en?.[key]; 

    if (translation === undefined) { // Check for undefined explicitly
      translation = fallback;
    }
    
    let result = translation || key; // Use key if translation and fallback are undefined

    if (interpolations && result) {
      Object.keys(interpolations).forEach(placeholderKey => {
        const regex = new RegExp(`\\{${placeholderKey}\\}`, 'g');
        result = result.replace(regex, String(interpolations[placeholderKey]));
      });
    }
    return result;
  };


  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, languages, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
